version: '3.3'
services:
    filebrowser:
        volumes:
            - '/home/ubuntu:/srv'
            - './filebrowser.db:/database/filebrowser.db'
            - './settings.json:/config/settings.json'
        environment:
            - PUID=$(id -u)
            - PGID=$(id -g)
        user: 'true'
        ports:
            - '1010:80'
        image: 'filebrowser/filebrowser:s6'
