#docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ee:latest

version: '3.6'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: always
    ports:
    - 8000:8000
    - 9443:9443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer_data:/data
    network_mode: nginx
